# Generated by Django 3.1.7 on 2021-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='data',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
