# Generated by Django 3.1.7 on 2021-05-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0002_hero_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='data',
        ),
        migrations.AddField(
            model_name='hero',
            name='campaign_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='campaign_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
