# Generated by Django 3.1.7 on 2021-05-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0003_auto_20210516_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ben_Tuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_resource_name', models.CharField(max_length=60)),
                ('campaign_name', models.CharField(max_length=60)),
                ('campaign_id', models.CharField(max_length=60)),
                ('ad_group_name', models.CharField(max_length=60)),
                ('metrics_clicks', models.CharField(max_length=60)),
                ('metrics_impressions', models.CharField(max_length=60)),
                ('metrics_ctr', models.CharField(max_length=60)),
                ('metrics_cpc', models.CharField(max_length=60)),
            ],
        ),
    ]
