# Generated by Django 3.1.7 on 2021-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0004_ben_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=60)),
                ('campaign_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_clicks', models.CharField(max_length=60)),
                ('metrics_impressions', models.CharField(max_length=60)),
                ('metrics_ctr', models.CharField(max_length=60)),
                ('metrics_cpc', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='ad_group_name',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='metrics_clicks',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='metrics_cpc',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='metrics_ctr',
        ),
        migrations.RemoveField(
            model_name='ben_tuition',
            name='metrics_impressions',
        ),
    ]
