# Generated by Django 3.1.7 on 2021-05-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0005_auto_20210523_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='campaign_id',
            new_name='campaignid',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='campaign_name',
            new_name='campaignname',
        ),
    ]
