# Generated by Django 3.1.7 on 2021-05-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0006_auto_20210523_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_resource_name', models.CharField(max_length=60)),
                ('campaign_name', models.CharField(max_length=60)),
                ('campaign_id', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['campaign_name'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Metrics',
            new_name='BenMetrics',
        ),
        migrations.DeleteModel(
            name='AdGroup',
        ),
        migrations.DeleteModel(
            name='Ben_Tuition',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.CreateModel(
            name='BenAdGroup',
            fields=[
                ('bencampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amplifyApi.bencampaign')),
                ('ad_group_name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['ad_group_name'],
                'abstract': False,
            },
            bases=('amplifyApi.bencampaign',),
        ),
    ]
