# Generated by Django 3.1.7 on 2021-05-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0007_auto_20210524_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenMetrics',
        ),
        migrations.AlterModelOptions(
            name='benadgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bencampaign',
            options={},
        ),
    ]
