# Generated by Django 3.1.7 on 2021-05-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0008_auto_20210524_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenMetrics',
            fields=[
                ('benadgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amplifyApi.benadgroup')),
                ('metrics_clicks', models.CharField(max_length=60)),
                ('metrics_impressions', models.CharField(max_length=60)),
                ('metrics_ctr', models.CharField(max_length=60)),
                ('metrics_cpc', models.CharField(max_length=60)),
                ('eachdate', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('amplifyApi.benadgroup',),
        ),
    ]
