# Generated by Django 3.1.7 on 2021-05-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0009_benmetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benmetrics',
            name='eachdate',
        ),
    ]
