# Generated by Django 3.1.7 on 2021-05-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0010_remove_benmetrics_eachdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benmetrics',
            name='benadgroup_ptr',
        ),
        migrations.DeleteModel(
            name='BenAdGroup',
        ),
        migrations.DeleteModel(
            name='BenCampaign',
        ),
        migrations.DeleteModel(
            name='BenMetrics',
        ),
    ]
