# Generated by Django 3.1.7 on 2021-05-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifyApi', '0011_auto_20210524_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_resource_name', models.CharField(max_length=60)),
                ('campaign_name', models.CharField(max_length=60)),
                ('campaign_id', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenAdGroup',
            fields=[
                ('bencampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amplifyApi.bencampaign')),
                ('ad_group_name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
            bases=('amplifyApi.bencampaign',),
        ),
        migrations.CreateModel(
            name='BenMetrics',
            fields=[
                ('benadgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amplifyApi.benadgroup')),
                ('metrics_clicks', models.CharField(max_length=60)),
                ('metrics_impressions', models.CharField(max_length=60)),
                ('metrics_ctr', models.CharField(max_length=60)),
                ('metrics_cpc', models.CharField(max_length=60)),
                ('datepulled', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('amplifyApi.benadgroup',),
        ),
    ]
